services:
  - type: web
    name: p2p-web-share-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://p2-pdatashare.vercel.app